project_params:
  entity: "kaicd"
  project: "EFA-DTI"
  max_epochs: 500
  seed: 42
  gpus: 1
  accelerator: "ddp"
  patience: 80
  monitor: "valid_mse"
  logging_interval: "step"
  save_path: "/raid/dataset/DTI/checkpoint/"
module_params:
  mol_dim: 128
  mol_n_layers: 8
  mol_n_heads: 8
  mol_attn: "softmax"
  act: "gelu"
  attn_dropout: 0.1
  dropout: 0.3
  graph_norm_type: "ln"
  fp_dims: [2048, 512, 128]
  prottrans_dims: [2048, 512, 256]
  output_dims: [2048, 256, 1]
  graph_pool: "mean_max"
  lr: 0.0001
  lr_anneal_epochs: 500
  weight_decay: 1e-8
  eps: 1e-16
  scheduler: "Lambda"
dataset_params:
  data_dir: "/raid/dataset/DTI/raw/"
  data_name: "BindingDB_IC50.ftr"
  unit: "nM"
  reset: False
  batch_size: 512
  seed: 42
  num_workers: 4
  pin_memory: True